#!/bin/sh
##############################################################################
# Gradle start up script for POSIX generated by Gradle.
##############################################################################

APP_HOME=$(cd "$(dirname "$0")" && pwd -P)
APP_NAME="Gradle"

if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec "$JAVACMD" $JAVA_OPTS $GRADLE_OPTS \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "$@"
